import { TableRH } from './tableRH';

export const TABLESRH: TableRH[] = [
	{
		id: 12345,
		name: '375837',
		flag: 'Samuel Nava Osorio',
		area: 'Samuel Nava Osorio',
		population: 'T12',
		grupo:'Zona VDM',
		conductor:'R. Chalco',
		tipo:'Chalco',
		nombre:'Recertificación',
		description:'9.3',
		calificacion:'9',
		cpractica:'Camión pesado',
		tipoL:'D',
		certificacion:'Interna'
	},
	{
		id: 1434160,
		name: '5539842',
		flag: 'Cristian Flores Norberto',
		area: 'Cristian Flores Norberto',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Chalco',
		tipo: 'Chalco',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1517916,
		name: '375837',
		flag: 'SAMUEL NAVA OSORIO',
		area: 'SAMUEL NAVA OSORIO',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Coacalco',
		tipo: 'Coacalco',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 12345678,
		name: '8492376',
		flag: 'Juan',
		area: 'Juan',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Cedis Sur',
		tipo: 'CEDIS Sur',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 3806642,
		name: '5044845',
		flag: 'Luis Linares Villar',
		area: 'Luis Linares Villar',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Tlalpan',
		tipo: 'Iztacalco',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión ligero',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1312670,
		name: '1312567',
		flag: 'Jose Armenegildo',
		area: 'Jose Armenegildo',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Reyes',
		tipo: 'Reyes',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1385829,
		name: '1385829',
		flag: 'Miguel Angel Lopez Serna',
		area: 'Miguel Angel Lopez Serna',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Cuautitlán',
		tipo: 'Cuautitlán',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 3806642,
		name: '5044845',
		flag: 'Luis Linares Villar',
		area: 'Luis Linares Villar',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Tlalpan',
		tipo: 'Iztacalco',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión ligero',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1312670,
		name: '1312567',
		flag: 'Jose Armenegildo',
		area: 'Jose Armenegildo',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Reyes',
		tipo: 'Reyes',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1385829,
		name: '1385829',
		flag: 'Miguel Angel Lopez Serna',
		area: 'Miguel Angel Lopez Serna',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Cuautitlán',
		tipo: 'Cuautitlán',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 12121212,
		name: '2323233',
		flag: 'Juan',
		area: 'Juan',
		population: 'Montacargas',
		grupo: 'Zona Pacifico',
		conductor: 'R. Montaña',
		tipo: 'Chilpancingo',
		nombre: 'Certificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Montacarga eléctrico',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 3783572,
		name: '123456',
		flag: 'MIGUEL',
		area: 'MIGUEL',
		population: 'T2',
		grupo: 'Zona Sureste',
		conductor: 'R. Tehuantepec',
		tipo: 'Matias Romero',
		nombre: 'Base 0',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 5573714,
		name: '5573714',
		flag: 'Agustin Garcia Landin',
		area: 'Agustin Garcia Landin',
		population: 'Montacargas',
		grupo: 'Zona VDM',
		conductor: 'R. Cedis Sur',
		tipo: 'CEDIS Sur',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Montacarga combustión',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 5620654,
		name: '5620654',
		flag: 'Miguel Lujan',
		area: 'Miguel Lujan',
		population: 'Montacargas',
		grupo: 'Zona VDM',
		conductor: 'R. Coacalco',
		tipo: 'Coacalco',
		nombre: 'Base 0',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Hombre a pie',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 3806642,
		name: '5044845',
		flag: 'Luis Linares Villar',
		area: 'Luis Linares Villar',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Tlalpan',
		tipo: 'Iztacalco',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión ligero',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1312670,
		name: '1312567',
		flag: 'Jose Armenegildo',
		area: 'Jose Armenegildo',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Reyes',
		tipo: 'Reyes',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1385829,
		name: '1385829',
		flag: 'Miguel Angel Lopez Serna',
		area: 'Miguel Angel Lopez Serna',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Cuautitlán',
		tipo: 'Cuautitlán',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 12121212,
		name: '2323233',
		flag: 'Juan',
		area: 'Juan',
		population: 'Montacargas',
		grupo: 'Zona Pacifico',
		conductor: 'R. Montaña',
		tipo: 'Chilpancingo',
		nombre: 'Certificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Montacarga eléctrico',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 3783572,
		name: '123456',
		flag: 'MIGUEL',
		area: 'MIGUEL',
		population: 'T2',
		grupo: 'Zona Sureste',
		conductor: 'R. Tehuantepec',
		tipo: 'Matias Romero',
		nombre: 'Base 0',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 5573714,
		name: '5573714',
		flag: 'Agustin Garcia Landin',
		area: 'Agustin Garcia Landin',
		population: 'Montacargas',
		grupo: 'Zona VDM',
		conductor: 'R. Cedis Sur',
		tipo: 'CEDIS Sur',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Montacarga combustión',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 5620654,
		name: '5620654',
		flag: 'Miguel Lujan',
		area: 'Miguel Lujan',
		population: 'Montacargas',
		grupo: 'Zona VDM',
		conductor: 'R. Coacalco',
		tipo: 'Coacalco',
		nombre: 'Base 0',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Hombre a pie',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 6478294,
		name: '92872094724',
		flag: 'Juan Perez',
		area: 'Juan Perez',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Tlalpan',
		tipo: 'Tlalpan',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 3402136,
		name: '4352516',
		flag: 'Jose Reinaldo',
		area: 'Jose Reinaldo',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Chalco',
		tipo: 'Chalco',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1312670,
		name: '354678',
		flag: 'Sergio Cázales',
		area: 'Sergio Cázales',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Reyes',
		tipo: 'Reyes',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión ligero',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 5573714,
		name: '5620654',
		flag: 'Miguel Lujan Guzman',
		area: 'Miguel Lujan Guzman',
		population: 'Montacargas',
		grupo: 'Zona VDM',
		conductor: 'R. Zaragoza',
		tipo: 'Viga',
		nombre: 'Base 0',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Montacarga eléctrico',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 5197066,
		name: '0',
		flag: 'Fatima Soto',
		area: 'Fatima Soto',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Tlalnepantla',
		tipo: 'Tlalnepantla',
		nombre: 'Certificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión ligero',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1434160,
		name: '5434017',
		flag: 'Geovanni Oscar Rodriguez Vallejo',
		area: 'Geovanni Oscar Rodriguez Vallejo',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Mixcoac',
		tipo: 'Mixcoac',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 5197066,
		name: '1',
		flag: 'Fatima',
		area: 'Fatima',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Tlalnepantla',
		tipo: 'Tlalnepantla',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1473999,
		name: '1693969',
		flag: 'Raul Castro Gutierrez',
		area: 'Raul Castro Gutierrez',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Zaragoza',
		tipo: 'Viga',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 1473999,
		name: '3534625',
		flag: 'Juan Antonio Albino Graciano',
		area: 'Juan Antonio Albino Graciano',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Zaragoza',
		tipo: 'Zaragoza',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión pesado',
		tipoL: 'D',
		certificacion: 'Interna'
	  },
	  {
		id: 23456,
		name: '9090909',
		flag: 'Hilda',
		area: 'Hilda',
		population: 'T2',
		grupo: 'Zona VDM',
		conductor: 'R. Coacalco',
		tipo: 'Coacalco',
		nombre: 'Recertificación',
		description: '9.3',
		calificacion: '9',
		cpractica: 'Camión ligero',
		tipoL: 'D',
		certificacion: 'Interna'
	  }
	
];
